theme: jekyll-theme-minimal
title: Walter Maisel
description: Bio & Codework
logo: https://raw.githubusercontent.com/waltmaisel/waltmaisel.github.io/master/16864779_1220728098047979_7740968290817278007_n.jpg
